s = '''GCTTGGAAGTGCTCGCAAAGATTGCGTTGTTAAGGAACATTCATGAGTGTCGCTCCTGCTGCATAGAATTTGTAACAAACAGTCAGGATGTGGTGTTCAAAGGTGGGGATCAGCGTGACTGGCGGTGTGTGTCGGCAGCTAGCCACTCTATCTCAAAAGTCCACGTATCAGGTTAACTGTGCGTCGCCGGCTATCTCCATCAAGGACCCGCAGCCGTCTGGTTGGAATTTTCACTATAAACGTATTGCCAGAGTAAGATGCCACCTCTTTCAGGTAGCGACAGCTAAGAACGTGTAATCTTGAGACGTGCTGCGGGCGGTCACTTTTACGCGTCAGAATGGTGATCCAGGGTGCATGGACCTCATGACTAGGCACCGCCTTAAGCTTCAGACCATGCGTACAAGCGGTCCGGAGAAGCTGTACATCCGACTCGGGTATGAGCGGACCTCCAAGACTTGATTCAAGGAGGCGCGACAGTCTAAGGTAAACATTCGCCGCGTAAATCGCGGAAGTTTTAGTTGGGGACGTACTGGGGTTAATGCAGCATACCTCCCGAGGCTAAGAGTTCACATCCTGCCACTAGCGATAGTGTTAGTGGTCAGTTCGGTGCGAGTCTCCTAATTCGTTACGGAACTGACTATGATCATTGGCTCGCTGACTATTTATCCCTGCGGAATGGGAATTGAGGTACACCCCTGGATTGACCACCGCGGCCGGACCTTAATCCACACAATCGAAGCTGTACTTGCCATGACGCTTATGTGTACCCCAGATTAAAACCTCTGGTGGGGGCCGGGTATGTACTATTTGGGGCATTCATGAACCAACTAGTAGCACCTCTAAAGTCGCAAAGATCACTCCTCCAGTAACCGGACTTCATTAGGACCTTCACGTGTCTCGTGTGCATATCTAACTCGGACCATTGCGCATTCCCGGATCGGCCGTCGCGTAT
'''

def ans(s): #returns number of adenine, cytosine, guanine, and thymine in a given DNA string
	a = s.count('A') #adenine count
	c = s.count('C') #cytosine count
	g = s.count('G') #guanine count
	t = s.count('T') #thymnine count
	return (str(a)+" " +str(c)+" "+str(g)+ " "+str(t)) #returns values as string
test = ans(s)
print(test)
