s = """CTGACGTTGGGTAAAGGAGCTATGCCTCACTAGGCTCTCTATCTGAGAACTCCGTCAATCTAAACCTCAAGCGGCAGTATAAAGTCTGTTACCCAAGGGTATCTAGCGAATAAGTGGTCAGAATGATGGCCCATCCACGATATTGGATTACCTATATACAATGGAAGTAATCATGGGCTGCGGACTATGGTTCCCGACACATTTCGCTTTATGTGGACGATGCGACGCGACGACGTCCAAGCGGTCGAGCTGAATCTGTATCCCATGCACGGCTTTTACACACACTCATCCAAAAGGCGTAAAGGCAAGACGGACACACTTCAGCTAGACACTTCAGGTATGACGATGTCGTGCCGAATACCCAAGGATATTACTTTATAAGTACGACTCGCCGCTCTCTCACTACCAGGGGCGTCCATGAGGCATAACGTATGAAGGGTAAACTCAGGCTGGGCCCGCTGGCCATAGAGATAATTCGGTGATCGGAGTAAAGGTCTTCGACTAGTCTCGCGCAGGCTACAGTGGGGTAGGCACGGACGGGCGGAACAGGCACTGCTCCCGCGCAAAGAGCAACAGACGTACCTGTAGCGCTCTGCAGATATGCTCCTTAGAAAGTGGTATTGCCATGAAGAGACAGTTGCCCCCCTTTCCTGAGGGCCTTTTGACGTACGGAGTAAACTTTAGGACAGTTATTCTAATGTTACCACTCTGCTGAATAGTCGTAAGTTCGAATAGGAGAAGGTTTAATCCTTTCGCTTAGAAAATTGATTCTCTTGTCCAATATTATCAGTGCGGGGGCGTAGATGTTTTATCAGTAATGGTATCTGTTGGG"""
def rever(str):
	i=0
	rev = ""
	j=0
	comp=""
	while i<len(str):
	 	rev=str[i:i+1]+rev
	 	i+=1
	while j<len(str):
		if rev[j:j+1]=="A":
			comp+="T"
		elif rev[j:j+1]=="C":
			comp+="G"
		elif rev[j:j+1]=="G":
			comp+="C"
		else:
			comp+="A"
		j+=1
	return comp
test = rever(s)
print(test)

